<?php

declare(strict_types=1);

namespace Nowo\TwigInspectorBundle\Command;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;

/**
 * Command to install Twig Inspector Bundle configuration file.
 *
 * @author Héctor Franco Aceituno <hectorfranco@nowo.com>
 * @copyright 2025 Nowo.tech
 */
#[AsCommand(
    name: 'nowo:twig-inspector:install',
    description: 'Creates the Twig Inspector Bundle configuration file'
)]
class InstallCommand extends Command
{
    private const CONFIG_TEMPLATE = <<<'YAML'
        # Twig Inspector Bundle Configuration
        # This file was automatically generated by the install command.
        # You can modify it according to your needs.

        nowo_twig_inspector:
            # List of template file extensions to inspect
            # Default: ['.html.twig']
            enabled_extensions:
                - '.html.twig'
                # Uncomment to also inspect other Twig files:
                # - '.twig'
                # - '.xml.twig'

            # Templates to exclude from inspection (supports wildcards with *)
            # Useful for excluding admin panels, email templates, or other sensitive areas
            excluded_templates:
                # - 'admin/*'           # Exclude all admin templates
                # - 'email/*.html.twig' # Exclude email templates
                # - 'security/*'        # Exclude security-related templates

            # Blocks to exclude from inspection (supports wildcards with *)
            # Useful for excluding large blocks like JavaScript or CSS
            excluded_blocks:
                # - 'javascript'        # Exclude 'javascript' block
                # - 'head_*'            # Exclude blocks starting with 'head_'
                # - 'styles'            # Exclude 'styles' block

            # Enable template usage metrics in Web Profiler
            # When enabled, collects statistics about templates and blocks used in each request
            # Default: true
            enable_metrics: true

            # Optimize performance by skipping output buffering when inspector is disabled
            # This reduces overhead when the inspector cookie is not set
            # Default: true
            optimize_output_buffering: true

            # Custom cookie name for enabling/disabling inspector
            # Default: 'twig_inspector_is_active'
            cookie_name: 'twig_inspector_is_active'

        YAML;

    /**
     * Constructor.
     *
     * @param string|null $projectDir The project directory (kernel.project_dir parameter)
     */
    public function __construct(
        private readonly ?string $projectDir = null
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addOption(
                'env',
                null,
                InputOption::VALUE_OPTIONAL,
                'The environment name (dev, test, prod)',
                'dev'
            )
            ->addOption(
                'force',
                'f',
                InputOption::VALUE_NONE,
                'Overwrite existing configuration file'
            )
            ->setHelp(
                <<<'HELP'
                    The <info>%command.name%</info> command creates the Twig Inspector Bundle configuration file and ensures routes are set up.

                                          <info>php %command.full_name%</info>

                    This command:
                      - Creates a configuration file at <comment>config/packages/{env}/nowo_twig_inspector.yaml</comment>
                      - Creates or updates <comment>config/routes.yaml</comment> with the bundle route import

                                        By default, it creates the file for the <comment>dev</comment> environment.
                                        You can specify a different environment:

                                          <info>php %command.full_name% --env=test</info>

                                        If the configuration file already exists, the command will ask for confirmation
                                        unless you use the <comment>--force</comment> option:

                                          <info>php %command.full_name% --force</info>

                    The bundle works without the configuration file using default values.
                    The routes file is required for the bundle to work properly.
                    HELP
            );
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $filesystem = new Filesystem();

        $env = $input->getOption('env') ?? 'dev';
        $force = $input->getOption('force');

        // Determine project directory
        $projectDir = $this->projectDir;
        if (null === $projectDir) {
            // Try to get from kernel or use current working directory
            $projectDir = getcwd() ?: '.';
        }

        $configDir = $projectDir . '/config/packages/' . $env;
        $configFile = $configDir . '/nowo_twig_inspector.yaml';

        // Check if file already exists
        if ($filesystem->exists($configFile) && !$force) {
            $io->warning(sprintf('Configuration file already exists: %s', $configFile));
            if (!$io->confirm('Do you want to overwrite it?', false)) {
                $io->info('Installation cancelled.');

                return Command::SUCCESS;
            }
        }

        // Create directory if it doesn't exist
        if (!$filesystem->exists($configDir)) {
            $filesystem->mkdir($configDir);
            $io->info(sprintf('Created directory: %s', $configDir));
        }

        // Write configuration file
        try {
            $filesystem->dumpFile($configFile, self::CONFIG_TEMPLATE);
            $io->success(sprintf('Configuration file created successfully: %s', $configFile));
        } catch (\Exception $e) {
            $io->error(sprintf('Failed to create configuration file: %s', $e->getMessage()));

            return Command::FAILURE;
        }

        // Create or update routes.yaml
        $routesFile = $projectDir . '/config/routes.yaml';
        $this->ensureRoutesFile($io, $filesystem, $routesFile);

        $io->note('You can now customize the configuration according to your needs.');
        $io->note('The bundle works with default values if you delete the config file.');

        return Command::SUCCESS;
    }

    /**
     * Ensures routes.yaml exists and contains the bundle route import.
     *
     * @param SymfonyStyle $io         The IO helper
     * @param Filesystem   $filesystem The filesystem helper
     * @param string       $routesFile The path to routes.yaml
     *
     * @return void
     */
    private function ensureRoutesFile(SymfonyStyle $io, Filesystem $filesystem, string $routesFile): void
    {
        $routeImport = <<<'YAML'

            # Twig Inspector Bundle routes
            when@dev:
                nowo_twig_inspector:
                    resource: '@NowoTwigInspectorBundle/Resources/config/routes.yaml'

            YAML;

        // If routes.yaml doesn't exist, create it
        if (!$filesystem->exists($routesFile)) {
            try {
                $filesystem->dumpFile($routesFile, $routeImport);
                $io->success(sprintf('Routes file created: %s', $routesFile));
            } catch (\Exception $e) {
                $io->warning(sprintf('Could not create routes file: %s', $e->getMessage()));
                $io->note('Please manually add the route import to config/routes.yaml:');
                $io->text($routeImport);
            }

            return;
        }

        // If routes.yaml exists, check if import is already there
        $content = file_get_contents($routesFile);
        if (false === $content) {
            $io->warning('Could not read routes.yaml file.');
            $io->note('Please manually add the route import to config/routes.yaml:');
            $io->text($routeImport);

            return;
        }

        // Check if the import already exists
        if (str_contains($content, 'NowoTwigInspectorBundle') || str_contains($content, 'nowo_twig_inspector')) {
            $io->info('Routes file already contains Twig Inspector Bundle import.');

            return;
        }

        // Append the import to existing file
        try {
            $filesystem->appendToFile($routesFile, $routeImport);
            $io->success('Added Twig Inspector Bundle route import to routes.yaml');
        } catch (\Exception $e) {
            $io->warning(sprintf('Could not update routes file: %s', $e->getMessage()));
            $io->note('Please manually add the route import to config/routes.yaml:');
            $io->text($routeImport);
        }
    }
}
