services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  nowo_twig_inspector.controller.open_template:
    class: Nowo\TwigInspectorBundle\Controller\OpenTemplateController
    arguments:
      - '@twig'
      - '@debug.file_link_formatter'
    public: true

  Nowo\TwigInspectorBundle\BoxDrawings:
    class: Nowo\TwigInspectorBundle\BoxDrawings

  Nowo\TwigInspectorBundle\Twig\TwigInspectorExtension:
    class: Nowo\TwigInspectorBundle\Twig\TwigInspectorExtension
    tags:
      - { name: twig.extension }

  Nowo\TwigInspectorBundle\Twig\HtmlCommentsExtension:
    class: Nowo\TwigInspectorBundle\Twig\HtmlCommentsExtension
    arguments:
      - '@request_stack'
      - '@router'
      - '@Nowo\TwigInspectorBundle\BoxDrawings'
      - '%nowo_twig_inspector.enabled_extensions%'
      - '%nowo_twig_inspector.excluded_templates%'
      - '%nowo_twig_inspector.excluded_blocks%'
      - '%nowo_twig_inspector.cookie_name%'
      - '%nowo_twig_inspector.max_injection_depth%'
      - '%nowo_twig_inspector.excluded_templates_regex%'
      - '%nowo_twig_inspector.excluded_templates_prefixes%'
      - '%nowo_twig_inspector.excluded_blocks_regex%'
      - '%kernel.debug%'
    tags:
      - { name: twig.extension }

  Nowo\TwigInspectorBundle\EventSubscriber\ControllerRenderSubscriber:
    class: Nowo\TwigInspectorBundle\EventSubscriber\ControllerRenderSubscriber
    arguments:
      - '@request_stack'

  Nowo\TwigInspectorBundle\EventSubscriber\ControllerCommentSubscriber:
    class: Nowo\TwigInspectorBundle\EventSubscriber\ControllerCommentSubscriber
    arguments:
      - '@request_stack'
      - '%nowo_twig_inspector.cookie_name%'
      - '%kernel.debug%'
    tags:
      - { name: kernel.event_subscriber }

  Nowo\TwigInspectorBundle\DataCollector\TwigInspectorCollector:
    class: Nowo\TwigInspectorBundle\DataCollector\TwigInspectorCollector
    arguments:
      - '@Nowo\TwigInspectorBundle\EventSubscriber\ControllerRenderSubscriber'
      - '@request_stack'
      - '@twig'
      - '%nowo_twig_inspector.cookie_name%'
      - '%nowo_twig_inspector.enable_metrics%'
      - '%nowo_twig_inspector.overlay_theme%'
      - '%nowo_twig_inspector.overlay_compact%'
      - '%nowo_twig_inspector.reduced_motion%'
      - '%nowo_twig_inspector.keyboard_shortcut%'
    tags:
      -
        name: data_collector
        template: '@NowoTwigInspector/Collector/template.html.twig'
        id: 'twig_inspector'
        # just before symfony twig collector
        priority: 260

  Nowo\TwigInspectorBundle\Command\InstallCommand:
    class: Nowo\TwigInspectorBundle\Command\InstallCommand
    arguments:
      - '%kernel.project_dir%'
    tags:
      - { name: console.command }

